In [51]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import SimpleRNN , Dense , Input

In [52]:
x = np.array([
    [1,2,3],
    [2,3,4],
    [3,4,5],
    [4,5,6],
])

y = np.array([4,5,6,7])

x = x.reshape(-1,3,1)

print(x)
print(x.shape)

# RNN 은 입력 3차원(data size, time_steps, features)
model = Sequential([
    Input(shape=(3,1)),
    SimpleRNN(2),
    Dense(1)
])

model.summary()

model.compile(
    loss = "mse",
    optimizer = "adam"
)

model.fit(
    x,
    y,
    epochs = 300,
    verbose=1
)

[[[1]
  [2]
  [3]]

 [[2]
  [3]
  [4]]

 [[3]
  [4]
  [5]]

 [[4]
  [5]
  [6]]]
(4, 3, 1)


Model: "sequential_32"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ simple_rnn_32 (SimpleRNN)       │ (None, 2)              │             8 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_29 (Dense)                │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 11 (44.00 B)

 Trainable params: 11 (44.00 B)

 Non-trainable params: 0 (0.00 B)

Epoch 1/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 674ms/step - loss: 28.5980
Epoch 2/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 28.5585
Epoch 3/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 28.5191
Epoch 4/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 28.4797
Epoch 5/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 28.4404
Epoch 6/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 28.4012
Epoch 7/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 28.3621
Epoch 8/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 28.3230
Epoch 9/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 28.2841
Epoch 10/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 28.2452
Epoch 11/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 28.2063
Epoch 12/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 28.1676
Epoch 13/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 28.1289
Epoch 14/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 28.0904
Epoch 15/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 28.0519
Epo

In [53]:
# 예측
x_pred = np.array([[5,6,7]]).reshape(-1,3,1)
# pred = model.predict(np.array([[5],[6],[7]]))
pred = model.predict(x_pred)

print(pred)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step
[[1.2750022]]


In [54]:
# 주식 종가 예측

x = np.array([
    [50000, 51000, 52000, 53000],
    [51000, 52000, 53000, 54000],
    [52000, 53000, 54000, 55000]
])

# 다음 날 종가
y = np.array([
    54000,
    55000,
    56000
])

x = x.reshape(-1,4,1)
print(x.shape)

# 모델 생성

# data_size = 3
# time_steps = 4
# features = 1 (종가만 사용)

model = Sequential([
    Input(shape=(4,1)),
    SimpleRNN(8, activation= "relu"),
    Dense(1)
])

model.summary()

model.compile(
    loss = "mse",
    optimizer = "adam"
)

model.fit(
    x,
    y,
    epochs = 500,
    verbose=1
)



(3, 4, 1)


Model: "sequential_33"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ simple_rnn_33 (SimpleRNN)       │ (None, 8)              │            80 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_30 (Dense)                │ (None, 1)              │             9 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 89 (356.00 B)

 Trainable params: 89 (356.00 B)

 Non-trainable params: 0 (0.00 B)

Epoch 1/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 622ms/step - loss: 4130088192.0000
Epoch 2/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 4097230592.0000
Epoch 3/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 4064824576.0000
Epoch 4/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 4032872448.0000
Epoch 5/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 4001372160.0000
Epoch 6/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 3970319616.0000
Epoch 7/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - loss: 3944516352.0000
Epoch 8/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 3919581952.0000
Epoch 9/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 3895028480.0000
Epoch 10/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 3870815232.0000
Epoch 11/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 3846907904.0000
Epoch 12/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 3823279104.0000
Epoch 13/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 3799904256.0000
Epoch 14/500
1/1 ━━━━━━━━━━━━━━━━

In [55]:
# 예측
# [53000, 54000, 55000, 56000]

x_pred = np.array([
    [53000, 54000, 55000, 56000]
])
x_pred = x_pred.reshape(-1,4,1)

pred = model.predict(x_pred)
print("다음 날 예상 종가",pred)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step
다음 날 예상 종가 [[57091.71]]


In [5]:
# RNN 을 푸시오.

import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Input, SimpleRNN, Dense

# ==========================
# 종가(Close) 데이터
# 최근 3일 종가 -> 다음날 종가
# ==========================

x = np.array([
    [[70000], [70500], [71000]],
    [[70500], [71000], [71500]],
    [[71000], [71500], [72000]],
    [[71500], [72000], [72500]],
    [[72000], [72500], [73000]]
], dtype=np.float32)

y = np.array([
    71500,
    72000,
    72500,
    73000,
    73500
], dtype=np.float32)

x = x.reshape(-1,3,1)
print(x.shape)

model = Sequential([
    Input(shape=(3,1)),
    SimpleRNN(8, activation= "relu"),
    Dense(1)
])

model.summary()

model.compile(
    loss = "mse",
    optimizer = "adam"
)

model.fit(
    x,
    y,
    epochs = 500,
    verbose=1
)
#  3일후 아래의 가격 다음알 을 예측하시오.

# 예측
x_pred = np.array([
    [[72500],
     [73000],
     [73500]]
])
x_pred = x_pred.reshape(-1,3,1)

pred = model.predict(x_pred)
print("다음 날 예상 종가",pred)
#    

(5, 3, 1)


Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ simple_rnn_1 (SimpleRNN)        │ (None, 8)              │            80 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │             9 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 89 (356.00 B)

 Trainable params: 89 (356.00 B)

 Non-trainable params: 0 (0.00 B)

Epoch 1/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 885ms/step - loss: 5097085952.0000
Epoch 2/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 4954830336.0000
Epoch 3/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - loss: 4814570496.0000
Epoch 4/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - loss: 4676340736.0000
Epoch 5/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - loss: 4540178944.0000
Epoch 6/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 4406114816.0000
Epoch 7/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - loss: 4274177536.0000
Epoch 8/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - loss: 4144391424.0000
Epoch 9/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - loss: 4016782080.0000
Epoch 10/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 3891368448.0000
Epoch 11/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 3768169216.0000
Epoch 12/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 3647197952.0000
Epoch 13/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 3528469248.0000
Epoch 14/500
1/1 ━━━━━━━━━━━━━━━━

In [ ]:
# Feature 1 : 온도(Temperature)
# Feature 2 : 습도(Humidity)

# 즉, 3일간의 온도와 습도를 보고 다음 날의 온도를 예측하는 예제

# [온도, 습도]
x = np.array([
    [[20,60],[21,61],[22,62]],
    [[23,63],[24,64],[25,65]],
    [[26,66],[27,67],[28,68]]
])

# 다음 날 온도
y = np.array([
    23,
    26,
    29
])

x = x.reshape(-1,3,2)
print(x.shape)

# ==========================================
# data_size = 3
# time_steps = 3
# features = 2
# ==========================================

model = Sequential([
    Input(shape=(3,2)),
    SimpleRNN(8,activation="relu"),
    Dense(1)
])

model.summary()

model.compile(
    loss = "mse",
    optimizer = "adam"
)

model.fit(
    x,
    y,
    epochs = 500,
    verbose=1
)


(3, 3, 2)


Model: "sequential_34"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ simple_rnn_34 (SimpleRNN)       │ (None, 8)              │            88 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_31 (Dense)                │ (None, 1)              │             9 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 97 (388.00 B)

 Trainable params: 97 (388.00 B)

 Non-trainable params: 0 (0.00 B)

Epoch 1/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 638ms/step - loss: 11693.5664
Epoch 2/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 11421.8857
Epoch 3/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 11154.7529
Epoch 4/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 10892.1904
Epoch 5/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 10634.2344
Epoch 6/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 10380.8916
Epoch 7/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 10132.1748
Epoch 8/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 9888.0869
Epoch 9/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 9648.6279
Epoch 10/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 9413.7930
Epoch 11/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 9183.5596
Epoch 12/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 8957.9111
Epoch 13/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 8736.8213
Epoch 14/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 8520.2578
Epoch 15/500
1/1 ━━━━━━━━━━━━━━━━━━

In [58]:
# 예측하시오
#    [[29,69],
#      [30,70],
#      [31,71]]

# 예측
x_pred = np.array([
    [
        [29,69],
        [30,70],
        [31,71]
    ]
])
x_pred = x_pred.reshape(-1,3,2)

pred = model.predict(x_pred)
print("다음 날 예상온도",pred)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step
다음 날 예상온도 [[28.303398]]


In [ ]:
# ==========================================
# 1. 데이터 준비
# ==========================================

# [키(cm), 몸무게(kg), 나이]
x = np.array([
    [[170,60,20], [171,61,21]],
    [[180,70,30], [181,71,31]],
    [[190,80,40], [191,81,41]],
    [[200,90,50], [201,91,51]]
])

# 다음 해 키
y = np.array([
    172,
    182,
    192,
    202
])

x = x.reshape(-1,2,3)
print(x.shape)

# ==========================================
# data_size = 4
# time_steps = 2
# features = 3
# ==========================================

model = Sequential([
    Input(shape=(2,3)),
    SimpleRNN(8,activation="relu"),
    Dense(1)
])

model.summary()

model.compile(
    loss = "mse",
    optimizer = "adam"
)

model.fit(
    x,
    y,
    epochs = 500,
    verbose=1
)

x_pred = np.array([
    [
        [210,95,25],
        [211,96,26]
    ]
])

x_pred = x_pred.reshape(-1,2,3)
pred = model.predict(x_pred)
print("다음 해 키",pred)


(4, 2, 3)


Model: "sequential_35"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ simple_rnn_35 (SimpleRNN)       │ (None, 8)              │            96 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_32 (Dense)                │ (None, 1)              │             9 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 105 (420.00 B)

 Trainable params: 105 (420.00 B)

 Non-trainable params: 0 (0.00 B)

Epoch 1/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 659ms/step - loss: 16942.2305
Epoch 2/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 16142.5078
Epoch 3/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 15367.1309
Epoch 4/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 14616.1562
Epoch 5/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 13889.5898
Epoch 6/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 13187.4023
Epoch 7/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 12509.5059
Epoch 8/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 11855.7910
Epoch 9/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 11226.0732
Epoch 10/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 10620.1641
Epoch 11/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 10037.8027
Epoch 12/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 9478.6992
Epoch 13/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 8942.5166
Epoch 14/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 8428.9023
Epoch 15/500
1/1 ━━━━━━━━━━━━━━

In [60]:
# [키(cm), 몸무게(kg), 나이]
x = np.array([
    [[170,60,20], [171,61,21]],
    [[180,70,30], [181,71,31]],
    [[190,80,40], [191,81,41]],
    [[200,90,50], [201,91,51]]
])

# 다음 해 키, 몸무게
y = np.array([
    [172,62],
    [182,72],
    [192,82],
    [202,92]
])

x = x.reshape(-1,2,3)
print(x.shape)

model = Sequential([
    Input(shape=(2,3)),
    SimpleRNN(8,activation="relu"),
    Dense(2) # 출력이 2개
])

model.summary()

model.compile(
    loss = "mse",
    optimizer = "adam"
)

model.fit(
    x,
    y,
    epochs = 500,
    verbose=1
)

x_pred = np.array([
    [
        [175,65,25],
        [176,66,26]
    ]
])

x_pred = x_pred.reshape(-1,2,3)
pred = model.predict(x_pred)
print("다음 해 키",pred)


(4, 2, 3)


Model: "sequential_36"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ simple_rnn_36 (SimpleRNN)       │ (None, 8)              │            96 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_33 (Dense)                │ (None, 2)              │            18 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 114 (456.00 B)

 Trainable params: 114 (456.00 B)

 Non-trainable params: 0 (0.00 B)

Epoch 1/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 618ms/step - loss: 8810.3027
Epoch 2/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 8617.2539
Epoch 3/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 8425.5400
Epoch 4/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 8235.2305
Epoch 5/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 8046.3975
Epoch 6/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 7859.1118
Epoch 7/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 7673.4434
Epoch 8/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 7489.4614
Epoch 9/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 7307.2324
Epoch 10/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 7126.8188
Epoch 11/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 6948.2817
Epoch 12/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 6771.6763
Epoch 13/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 6597.0518
Epoch 14/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 6424.4556
Epoch 15/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 2